/* 
 * DevOps Vault API
 *
 * The purpose of this application is to provide a simple service for storing and getting secrets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = DevOpsVault.SDK.Core.Client.OpenAPIDateConverter;

namespace DevOpsVault.SDK.Core.Model
{
    /// <summary>
    /// MemberRequest to add or delete user to groups
    /// </summary>
    [DataContract]
    public partial class MemberRequest :  IEquatable<MemberRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MemberRequest" /> class.
        /// </summary>
        /// <param name="memberNames">Names.</param>
        public MemberRequest(List<string> memberNames = default(List<string>))
        {
            this.MemberNames = memberNames;
        }
        
        /// <summary>
        /// Names
        /// </summary>
        /// <value>Names</value>
        [DataMember(Name="memberNames", EmitDefaultValue=false)]
        public List<string> MemberNames { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MemberRequest {\n");
            sb.Append("  MemberNames: ").Append(MemberNames).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MemberRequest);
        }

        /// <summary>
        /// Returns true if MemberRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of MemberRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MemberRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.MemberNames == input.MemberNames ||
                    this.MemberNames != null &&
                    input.MemberNames != null &&
                    this.MemberNames.SequenceEqual(input.MemberNames)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.MemberNames != null)
                    hashCode = hashCode * 59 + this.MemberNames.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
