/* 
 * DevOps Vault API
 *
 * The purpose of this application is to provide a simple service for storing and getting secrets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = DevOpsVault.SDK.Core.Client.OpenAPIDateConverter;

namespace DevOpsVault.SDK.Core.Model
{
    /// <summary>
    /// PolicyUpdate struct
    /// </summary>
    [DataContract]
    public partial class PolicyUpdate :  IEquatable<PolicyUpdate>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PolicyUpdate" /> class.
        /// </summary>
        /// <param name="policy">policy.</param>
        /// <param name="serialization">serialization.</param>
        public PolicyUpdate(string policy = default(string), string serialization = default(string))
        {
            this.Policy = policy;
            this.Serialization = serialization;
        }
        
        /// <summary>
        /// Gets or Sets Policy
        /// </summary>
        [DataMember(Name="policy", EmitDefaultValue=false)]
        public string Policy { get; set; }

        /// <summary>
        /// Gets or Sets Serialization
        /// </summary>
        [DataMember(Name="serialization", EmitDefaultValue=false)]
        public string Serialization { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PolicyUpdate {\n");
            sb.Append("  Policy: ").Append(Policy).Append("\n");
            sb.Append("  Serialization: ").Append(Serialization).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PolicyUpdate);
        }

        /// <summary>
        /// Returns true if PolicyUpdate instances are equal
        /// </summary>
        /// <param name="input">Instance of PolicyUpdate to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PolicyUpdate input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Policy == input.Policy ||
                    (this.Policy != null &&
                    this.Policy.Equals(input.Policy))
                ) && 
                (
                    this.Serialization == input.Serialization ||
                    (this.Serialization != null &&
                    this.Serialization.Equals(input.Serialization))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Policy != null)
                    hashCode = hashCode * 59 + this.Policy.GetHashCode();
                if (this.Serialization != null)
                    hashCode = hashCode * 59 + this.Serialization.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
